apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-config
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  MONGODB_URI: "mongodb://mongo:27017"
  MONGODB_DB: "yelp_prototype"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-secrets
type: Opaque
stringData:
  SECRET_KEY: "change_me_in_prod"

